### ISSUE TITLE
Use FormattedMessage instead of Message

### ISSUE THREAD

**Issue by snakefoot** [travelgateX/NLog.Targets.PostTarget#1]
`LogEvent.FormattedMessage` returns the result of the string.Format using format-args, where `LogEvent.Message` returns the raw message-template.

https://github.com/XML-Travelgate/NLog.Targets.PostTarget/blob/a754644410abbaf460ba0f0ee2833735cda6cb7d/src/NLog.Targets.PostTarget/PostTarget.cs#L105

If wanting to be very advanced then configure the Layout in target-constructor:

`Layout = "${message}"`

And use the following `Layout.Render(ev.LogEvent)` instead of `ev.LogEvent.Message`

**Comment by bolivernoguera** [comment]
@snakefoot  Thanks! I will add it 👍

**Comment by bolivernoguera** [comment]
Done

**Comment by carlostur** [comment]
Done
